### ISSUE TITLE
Allow Different Opacities for L.WMS.Source Sublayers

### ISSUE THREAD

**Issue by JJeurissen** [heigeo/leaflet.wms#10]
Andrew you mentioned this in your email.  I have a series of layers using the same service, but they all have different opacities.  Instead of using the same L.WMS.Source I'm forced to add each one as a L.WMS.Overlay.  I would like to be able to support having opacities defined per layer so that only a single request is called to the server instead of a request per layer.

**Comment by sheppard** [comment]
Yes, this would be nice to have - but probably will require server support.  If the layer opacities don't change on demand, you could just set them in the mapfile.  Otherwise, one workaround might be to use a different Source for each group of layers with the same opacity level, assuming there aren't very many levels.

**Comment by sheppard** [comment]
Closing this for now as it's probably not something we can address within JavaScript.
