### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by jenseva** [heigeo/leaflet.wms#38]
It looks like somethings not right with the example from git. The time slider is static. I copied over the code from your working example on github pages and that is working fine for me, but the clone has the broken slider.

**Comment by sheppard** [comment]
Is this still not working?  Note that the WMS service we used for the example is fairly slow so you might not see everything right away.

**Comment by MaxymVlasov** [comment]
@sheppard I waited about 5 minutes
Example still not working.

![](https://pp.vk.me/c639425/v639425502/92d8/u7sfmmJ-z3w.jpg)

**Comment by slead** [comment]
The example at http://heigeo.github.io/leaflet.wms/examples/ is currently failing because the underlying services from National Map are missing - https://services.nationalmap.gov/arcgis/rest/services/GlobalMap doesn't list any services:

![image](https://cloud.githubusercontent.com/assets/133596/23533644/239a3932-0007-11e7-9f4e-297997a6a1ea.png)

**Comment by sheppard** [comment]
I switched it to use terrestris layers as suggested in #27.
